import Head from 'next/head';
import localFont from "next/font/local";
import "./globals.css";
import {Roboto,Inner} from 'next/font/google'
import HeaderHome from './components/HeaderHome';


const roboto = Roboto({subsets:['latin'], weight:['300','400','700']});
// const inner = Inner({subsets:['latin'], weight:['300','400','700']});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Thêm Bootstrap CSS từ CDN */}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossOrigin="anonymous"></link>
        <link rel="canonical" href='https://shoeshop-teal.vercel.app'/>
      </head>
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body className={`${roboto.className} ${geistSans.variable} ${geistMono.variable}`}>
        <HeaderHome/>
        {children}
        {/* Thêm Bootstrap JavaScript từ CDN */}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
